#!/bin/sh

SCRIPT=/home/ec2-user/ocr-processing-service/script.py
NAME=ocr-processing-service
DESC="OCR Processing Service"
PIDFILE=/var/run/ocr-processing-service.pid
LOGFILE=/var/log/ocr-processing-service.log


set -e

case "$1" in
  start)
    if [ -f $PIDFILE ]
    then
      echo -n "$PIDFILE exists, process is already running or crashed\n"
    else
      touch $PIDFILE $LOGFILE
      chown ec2-user:ec2-user $PIDFILE $LOGFILE
      echo -n "Starting OCR Processing Service...\n"
      python $SCRIPT >> $LOGFILE 2>&1 &
      echo "$!" > $PIDFILE
    fi
    ;;    
    
  stop)
    echo "Stopping $DESC"
    if [ ! -e "$PIDFILE" ]
    then
      echo "failed"
    else
      kill -9 $(echo $PIDFILE)
      echo "$NAME stopped"
      rm -f $PIDFILE
    fi
    ;;

  restart|force-reload)
    ${0} stop
    ${0} start
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0